### ISSUE TITLE
Dependabot Job fails after taking 60 minutes

### ISSUE THREAD

**Issue by ConstantinEilebrecht** [tinglesoftware/dependabot-azure-devops#1356]
**Describe the bug**
The Azure DevOps Pipeline running Dependabot V2 for an Angular project exceeds the maximum run time of 60 minutes, causing the job to fail.

**Categorization**
- [X] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**
URL: sorry private company repo

**To Reproduce**
1. Trigger the pipeline.
2. Observe as the build time exceeds 60 minutes before completion.

**Expected behavior**
The pipeline should complete successfully within the allotted 60 minutes.

**Screenshots**
![image](https://github.com/user-attachments/assets/493e3c8c-8b3b-4d62-b933-e65012a98e0f)

**Extension (please complete the following information):**
- Host: Azure DevOps
- Version: 1.35.1.923 (Latest)

**Server (please complete the following information):**
- Region: West Europe
- Version: Dev19.M244.1 (AzureDevOps_M244_20240924.6)

**Additional context**
I also noticed in the job logs that the github api rate limit is reached quite often. (712 times)

```
2024-09-27T18:37:21.5657248Z   proxy | 2024/09/27 18:37:21 [952] Remote response: {"message":"API rate limit exceeded for xxx.xx.xx.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
2024-09-27T18:37:21.5695270Z updater | 2024/09/27 18:37:21 ERROR <job_update_0_npm_and_yarn_all> Error while generating PR message: GET https://api.github.com/repos/angular/angular/contents/packages/language-service: 403 - API rate limit exceeded for xxx.xx.xx.x . (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
2024-09-27T18:37:21.5697807Z updater | 2024/09/27 18:37:21 ERROR <job_update_0_npm_and_yarn_all> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/octokit-7.2.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
2024-09-27T18:37:21.5698373Z updater | /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/faraday-2.7.11/lib/faraday/middleware.rb:18:in `block in call'
```

**Comment by rhyskoedijk** [comment]
Thanks for the report.
The rate-limiting issue should hopefully be fixed by https://github.com/tinglesoftware/dependabot-azure-devops/pull/1362.

**Comment by ConstantinEilebrecht** [comment]
I tried to use a azure devops service connection and a github access token with the input params:

```
- task: dependabot@2
  inputs:
   gitHubConnection: 'github'
   gitHubAccessToken: $(GITHUB_ACCESS_TOKEN)
```

I then checked the current github api ratelimit for the user during the pipeline job. The ratelimit didn't change.

`curl -H "Authorization: token YOUR_GITHUB_TOKEN" https://api.github.com/rate_limit`

Hopefully your changes pass the github credentials correctly.

**Comment by ConstantinEilebrecht** [comment]
The job still takes a lot of time.
I only enabled the Backend Part of my project with the nuget dependencies. It takes 45 minutes
The job break with my Frontend dependencies after 60 Minutes.

This is the flame graph of my be dependencies scan:
`4_dependabot-update-0-nuget-all-flamegraph.html`
![image](https://github.com/user-attachments/assets/039c6d76-50cb-4f73-b090-420bf750f7bf)

**Comment by rhyskoedijk** [comment]
Thanks @ConstantinEilebrecht, yes performance is common theme unfortunately across all versions since about v1.24 when Dependabot switch over to a native C# NuGet updater. It can be especially slow if there are a lot of projects or a lot of packages to update. The good news is that there is a complete re-write of the NuGet updater coming soon in dependabot-core; Hopefully this will make NuGet update much more efficient in the near future.

Would you be comfortable sharing the full flame graph html report? It's a bit hard to drill in to sections from the screenshot, the interactive version is a bit more usable. The report doesn't contain any info about your DevOps environment, just stack info from the dependabot-core library. If there isn't any obvious answer in the report, the next step might be to submit this issue to the dependabot-core project, who will be able to understand the issue (and report) a lot better that I do.

In the short-term, here are some _possible_ work around options, if you haven't considered them already:
- Is it possible to [extend the pipeline timeout](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts)? 
- Is it possible to split the updates over multiple stages/agents using the [targetUpdateIds task input option](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/extension/README.md#task-parameters), one stage for NuGet, one stage for NPM?

**Comment by ConstantinEilebrecht** [comment]
Hi, @rhyskoedijk 

thank you for the forecast reagarding dependabot core and the updater engine.

Here is the full flamegraph report. My Chrome Browser is not able to render this. Does yours :) ? So only provided the screenshort.
[flamegraph.zip](https://github.com/user-attachments/files/17227742/flamegraph.zip)

Thanks for the hints fighting against the pipeline timeouts. I'll have to check.

**Comment by Ossiam** [comment]
@ConstantinEilebrecht @rhyskoedijk I can confirm that using multiple agents with targetUpdateIds works wonderfully.
In the image below I use 3 agents pointing to 3 different targetUpdateIds, without that it would indeed timeout. 
![{6D5B2C7D-F518-4F1B-8841-4FD7D91B4EC1}](https://github.com/user-attachments/assets/a6d7e5c5-a36c-46fc-8995-0577b6a66f1c)

**Comment by ConstantinEilebrecht** [comment]
@Ossiam 
Thanks. Yes this work's. That's kind of a workaround. But it's timeconsuming to configure.

**Comment by rhyskoedijk** [comment]
@ConstantinEilebrecht I wasn't able to gain much insight from the flame graph; however, I don't have a lot of experience analyzing these so that isn't saying much. I know it isn't the best answer, but I would suggest opening an issue in [dependabot-core](https://github.com/dependabot/dependabot-core/issues) and attaching the flame graph to see if they are able to provide any suggestions on what might be wrong.

I did a search for similar issues (NuGet update timeouts) and found these issues which might be worth bumping with your experience too:
- https://github.com/dependabot/dependabot-core/issues/9375#issuecomment-2140204218
- https://github.com/dependabot/dependabot-core/issues/4991

**Comment by rhyskoedijk** [comment]
If you haven't already consider this, you might be able to resolve the timeout problem by doing a manual update of your packages in Visual Studio as a once-off. I recently enabled Dependabot in a NuGet project that took about 5hrs to run and in the end I just decided to manually update the packages and then turn Dependabot on after the manual update; The pipeline runtime dramatically reduced. It's not a perfect solution, but it at least now allows the project to successfully complete it's weekly update without timing out.
