### ISSUE TITLE
Why Azure API_VERSION = 7.1

### ISSUE THREAD

**Issue by onederey** [tinglesoftware/dependabot-azure-devops#1423]
What is the reason to use API_VERSION = 7.1, can we downgrade it to 7.0?

Got an error `The requested REST API version of 7.1 is out of range for this server. The latest REST API version this server supports is 7.0.`

**Comment by rhyskoedijk** [comment]
@onederey thanks for the report; 

7.1 was used as this was the latest available in Azure DevOps Services at the time of developing TaskV2. In hindsight, for maximum compatibility, we should drop this to the lowest version that supports the required APIs.

This will be fixed in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1425

**Comment by onederey** [comment]
thanks!

**Comment by mburumaxwell** [comment]
API Version 7.1 is because of reapproval.

See:
- https://github.com/tinglesoftware/dependabot-azure-devops/pull/1131
- https://github.com/tinglesoftware/dependabot-azure-devops/pull/1132
- https://github.com/tinglesoftware/dependabot-azure-devops/issues/1069

**Comment by rhyskoedijk** [comment]
@onederey compatibility has been extended back to API version 5.0. The only exception is that the `autoApprove` will only work if on API version 7.1 servers; If you require this feature, you will need to upgrade.

See [task input documentation](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/extension/README.md#task-parameters):

![image](https://github.com/user-attachments/assets/54af7ace-17f6-429a-8b5b-2cc06a764a76)

**Comment by onederey** [comment]
thanks!
