### ISSUE TITLE
BUG: key not found: "DEPENDABOT_JOB_PATH" (KeyError)

### ISSUE THREAD

**Issue by rgrace-puck** [tinglesoftware/dependabot-azure-devops#1489]
Version: 1.38

```
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.288.0/lib/dependabot/nuget/file_parser.rb:64:in `fetch': key not found: "DEPENDABOT_JOB_PATH" (KeyError)
Did you mean?  "DEPENDABOT_UPDATER_VERSION"
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.288.0/lib/dependabot/nuget/file_parser.rb:64:in `job_file_path'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.288.0/lib/dependabot/nuget/file_parser.rb:37:in `parse'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/call_validation.rb:278:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11663/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:545:in `<main>'
```

**Comment by rhyskoedijk** [comment]
@rgrace-puck thanks for the report. It looks like this has broken due to a recent change to the NuGet updater in [dependabot-core  v0.286.0](https://github.com/dependabot/dependabot-core/releases/tag/v0.286.0). I see you are using Task V1, is it possible to use Task V2, or is that not an option?

@mburumaxwell it looks like https://github.com/dependabot/dependabot-core/pull/10868 changed the NuGet updater to parse some of the job file from disk, which breaks the Task V1 scripts since they use environment variables rather than a job file. I imagine to fix this, `update_script.rb` and `update_script_vnext.rb` would need to write a job file prior to starting the update, which is not a one-liner fix. What are your thoughts on this?

**Comment by mburumaxwell** [comment]
@rgrace-puck 
The temporary workaround is to set dockerImageTag to 1.38.1 as I try get a fix.

@rhyskoedijk 
I didn't see this in the list of changes. Maybe I rushed it.
It doesn't make much sense to continue investing effort into v1 so I think reverting the related changes and then removing auto updates should do.

Actually, I'd want to remove v1 all together but I reckon it will break stuff for some people, like those using security-only updates. Maybe sending a removal warning message will be sufficient then removal in 60 days.

What are your views?

**Comment by rhyskoedijk** [comment]
> Actually, I'd want to remove v1 all together but I reckon it will break stuff for some people, like those using security-only updates. Maybe sending a removal warning message will be sufficient then removal in 60 days.

I think it is worth keeping V1 around so long as it doesn't add any maintenance overhead. Now that you have stopped dependabot-omnibus updates, it should continue to work so long as the docker images stay online. 

I have finished the first cut for security-only updates in V2, so hopefully getting V2 feature complete isn't too far away now :crossed_fingers:
