### ISSUE TITLE
Possibility to make multiply updates with one PR instead of one PR per Update

### ISSUE THREAD

**Issue by schamal2205** [tinglesoftware/dependabot-azure-devops#240]
We have multiple internal Nuget Packages and if there are - whitin the dependency tree - multiple updates the current setting with one Pull Request per Update causes hundreds of Pull Requests in our "master" Repository. 

Is there a possiblity to collect multiple updates within one Pull Request or could this be a feature to be implemented? 

I'm not very familiar with ruby, but if you accept changes from other i could take a look by myself when i have time to implement a feature/setting for this one?

**Comment by mburumaxwell** [comment]
Hi @schamal2205 indeed contributions are accepted and encouraged. However, this particular change may be best suited for the [core repository](https://github.com/dependabot/dependabot-core) since it changes how dependabot works. This extension just provides support for the core dependabot features into Azure DevOps.

**Comment by poyyaren** [comment]
The dependabot-core repository has this feature: [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups). However, it seems that dependabot-azure-devops does not support those options, as we are seeing multiple PRs being created. The issue is also documented in [this Stackoverflow question](https://stackoverflow.com/questions/78948889/how-to-configure-dependabot-on-azure-devops-to-create-only-one-pr-for-minor-patc), which links back to this issue...

**Comment by rhyskoedijk** [comment]
@poyyaren support for the "groups" option was added in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1186, but only works if you opt-in to the "vNext" update script. You can enable group support by setting `useUpdateScriptvNext: true` in your task input config.

**Comment by poyyaren** [comment]
@rhyskoedijk thank you, for your input. That solved the issue for me.
