### ISSUE TITLE
Incorrect handling of csproj files

### ISSUE THREAD

**Issue by bjuraga** [tinglesoftware/dependabot-azure-devops#261]
In case the csproj includes different packages per target framework, the PRs created make no sense.
Here is the example of updating Microsoft.Extensions.Logging from 3.0.0 to 6.0.0
```xml
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
</ItemGroup>
```

This might not be possible by dependabot itself, but wanted to give it a shot in case you made some improvements on top of it.

And thanks for the extension, really makes dependabot an easy to use CI tool.

**Comment by mburumaxwell** [comment]
@bjuraga Thanks for your appreciation.
Unfortunately, dependabot code does not support target framework selection because of the amount of work that would be required without loading NuGet tools. This has been described at [#2733](https://github.com/dependabot/dependabot-core/issues/2733)

Maybe another tool could do exactly what you want? [NuKeeper](https://github.com/NuKeeperDotNet/NuKeeper) perhaps?
