### ISSUE TITLE
Dependabot::RepoNotFound error

### ISSUE THREAD

**Issue by OneCyrus** [tinglesoftware/dependabot-azure-devops#27]
when running this task on a microsoft hosted agent i get this failure (vmImage: ubuntu-latest). On our self hosted agent it works. any idea what could be the issue?

```
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.1
/vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:444:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:440:in `default_branch_for_repo'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:151:in `<main>'
/vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/clients/azure.rb:187:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/clients/azure.rb:46:in `fetch_default_branch'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:442:in `default_branch_for_repo'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.126.1/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.126.1/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:151:in `<main>'
```

**Comment by jasonnissen** [comment]
@OneCyrus I encountered the same issue. I was able to resolve the issue by changing my Azure DevOps organization to use the new URL (https://dev.azure.com). I changed it under Organization Settings...General...Overview...toggled on Use the new URL: https://dev.azure.com.

**Comment by mburumaxwell** [comment]
@OneCyrus , run the pipeline with the `Enable system diagnostics` option enabled and share the logs output.

**Comment by OneCyrus** [comment]
the setting of @jasonnissen fixed this issue. thanks!

**Comment by mogryo** [comment]
Hello! First of all, thanks for trying to bring Dependabot to Azure.

But now, the issue.
I encountered same error. Unfortunately I cannot change Organisation Settings, to use new URL...  

Enabling system diagnostics show no error logs considering this issue. First same errors in Ruby, and afterwards only error log is 
`##[error]The process '/usr/bin/docker' failed with exit code 1`

What's interesting, after the errors in Ruby code, and before the docker exit with 1, I have logs about environment:
```
Using 'old-format.url.com' as hostname
Fetching npm_and_yarn dependency files for organization-name/project-name/_git/repo-name
Targeting 'master' branch under '/' directory
Using 'bump_versions' versioning strategy

```
All the information is correct. Only strange thing is, I would expect them before Ruby code is executed. Isn't it possible Ruby code runs before those variables are set, and uses defaults settings? (by the way, default hostname is indeed dev.azure.com as is written in https://github.com/tinglesoftware/dependabot-azure-devops/tree/main/src/docker, so it would explain why switching the whole organisation to it, helps the issue).

**Comment by mogryo** [comment]
Short update, checked some more source code and logs, and can definitely say docker runner is executed with all correct variables. My bad for making wrong assumption. 

Although very strange that change of organisation hostname somehow helps, but unfortunately as I said, that solution is impossible for me.

**Comment by mburumaxwell** [comment]
Hello,

It has taken a while to di through the code for dependabot to find out what the issue is. Unfortunately, dependabot-core does not support getting code from the `{organization}.visualstudio.com` based URLs. I had to do repeated tests with our old URL (xxx.visualstudio.com) and with EXCON debug enabled to understand the issue more. I'll attempt to explain it to you, I am no ruby expert but I'll do my best.

The error occurs on the first HTTP call done [here](https://github.com/dependabot/dependabot-core/blob/e207e5810bd54dd01c97c49aa0bb90a463ef260f/common/lib/dependabot/clients/azure.rb#L54-L60). This is a call to get the default branch for the repository (the same error happens in the first comment in this issue. In particular, the exception is thrown from [line 59](https://github.com/dependabot/dependabot-core/blob/e207e5810bd54dd01c97c49aa0bb90a463ef260f/common/lib/dependabot/clients/azure.rb#L59) because the response gotten from Azure DevOps is a 401 (Unauthorized). Dependabot makes a request to `https://xxx.visualstudio.com/{organization}/{project}/_apis/git/repositories/{repository-name}` which is a wrong URL. Instead, this should have been `https://xxx.visualstudio.com/{project}/_apis/git/repositories/{repository-name}` (the `{organization}/` segment should not be there). See [line 56](https://github.com/dependabot/dependabot-core/blob/e207e5810bd54dd01c97c49aa0bb90a463ef260f/common/lib/dependabot/clients/azure.rb#L56) fixes the organization and a forward slash always. Setting the organization to null will still not work.

Further, digging into the implementation for the creating the source [here](https://github.com/dependabot/dependabot-core/blob/e207e5810bd54dd01c97c49aa0bb90a463ef260f/common/lib/dependabot/source.rb#L26-L30) and [here](https://github.com/dependabot/dependabot-core/blob/e207e5810bd54dd01c97c49aa0bb90a463ef260f/common/lib/dependabot/source.rb#L97-L108), there is no way to create the `Dependabot::Source` without specifying the organization as [done in the script](https://github.com/tinglesoftware/dependabot-azure-devops/blob/d8b578add42d3749f44ff0bb98f8f25250a050b2/src/script/update-script.rb#L13). Various attempts did not work either.

This leaves you with two options:
1. Change your organization to the new hostname/domain. Enabling the new hostname should not affect the older one. We still have access to the old hostname, years later. *easiest option*
2. Create an issue/PR for the functionality in the [dependabot-core](https://github.com/dependabot/dependabot-core) repository. Once the support is available in the upstream repository, they will appear here too.

Hope this explanation helps
