### ISSUE TITLE
.NET package transitive vulns

### ISSUE THREAD

**Issue by johnmccormick99** [tinglesoftware/dependabot-azure-devops#338]
Hi,

If I run dotnet list package --include-transitive  --vulnerable in Visual Studio I am informed of vulnerable transitive dependencies and can remediate by adding a package reference in the affected project. 

Dependabot does not detect the package transitive vulns.

I am I correct in thinking that Dependabot only handles first-level dependencies?

thanks,

**Comment by mburumaxwell** [comment]
@johnmccormick99 this is indeed correct for NuGet in dependabot. I suspect this is the case primarily because we do not commit any file stating the transitive dependencies into source control unlike is the case with npm with `project-lock.json`, ruby with `Gemfile.lock`, etc. In .NET the file with this information is `project.assets.json` usually in the `obj` folder of the project.

Let me know if this helps.
Closing as answered; you can reopen if need be.
