### ISSUE TITLE
PR auto approval / work item linking

### ISSUE THREAD

**Issue by OneCyrus** [tinglesoftware/dependabot-azure-devops#34]
currently we are using a git flow process to review our changes. This means we have PR policies which require to have an approval and a linked work item for every PR. It would be nice to have a feature which links a fixed work item to every PR and set the PR to approve/auto-complete.

**Comment by mburumaxwell** [comment]
@OneCyrus how do you suggest this be done?

**Comment by mburumaxwell** [comment]
@OneCyrus how do you suggest this be done?

**Comment by danquirk** [comment]
The way I would do this (/have) is not to re-use one fixed work item but rather have the script create a new work item per PR with a work item title that matches the PR title. This is nice even for folks who don't require linked work items since then your project will have a more accurate build payload in ADO.

@OneCyrus the alternative way you can do is to add an additional step in your pipeline that runs after the dependabot task(s) which 1) finds active dependabot PRs in your repo (search for active PRs with title contains "Bump" || "Update" and labels contains "dependencies") 2) set them to auto-complete 3) create a new work item for the PR then link it. You can do this quite easily with the ADO CLI. 

Something like this in a powershell task in an ADO pipeline:

```
      Write-Host "Login to ADO CLI"
      $pat = [System.Environment]::GetEnvironmentVariable($repo.patVariableName)
      $pat | az devops login
      az devops configure --defaults organization=https://$organization.visualstudio.com project=$project --use-git-aliases true

      Write-Host "Process active PRs"
      $activePRs = az repos pr list --org "https://dev.azure.com/$organization" --project $project --repository $repoName --status active --target-branch $branchName -o json --only-show-errors | ConvertFrom-Json

      foreach($pr in $activePRs) {
          $labels = $pr.labels | select -ExpandProperty name
          if($pr.title.StartsWith("Bump") -and $labels.Contains("dependencies")) {
              Write-Host "Dependabot PR $($pr.pullRequestId) $($pr.title)"
              
              $linkedWorkItems = az repos pr work-item list --id $pr.pullRequestId -o json --only-show-errors | ConvertFrom-Json
              if(-not $linkedWorkItems) {
                $fields = "System.Tags=Dependabot"
                $createdWorkItem = az boards work-item create --title "Dependabot ($repoName): $($pr.title)" --type "Task" --org "https://dev.azure.com/$organization" --project $project --fields $fields -o json --only-show-errors | ConvertFrom-Json
                Write-Host "Created work item $($createdWorkItem.id) - $($createdWorkItem.title)"
                Write-Host "Link work item to PR"

                az repos pr work-item add --id $pr.pullRequestId --work-items $createdWorkItem.id --only-show-errors | Out-Null
              }

              Write-Host "Set autocomplete"
              az repos pr update --id $pr.pullRequestId --auto-complete true --org "https://dev.azure.com/$organization"  --only-show-errors | Out-Null
              Write-Host "Completed work for $($pr.pullRequestId)"
          }
      }
```

If you have some system accounts with permission to approve pull requests you could even add a couple lines to add their votes/approval to the PRs so your dependabot PRs are truly automatic as long as your PR build validation passes.

Obviously you could also do this with the relevant ADO APIs and not take a dependency on the ADO CLI but it's so much easier to use the CLI for the most part (it's pre-installed on the normal ADO Hosted Agents and easy to quickly install as part of the pipeline execution if you have a different pool).

**Comment by michael-letcher** [comment]
Yes this is a big blocker for us. Would love to see this added.

**Comment by mburumaxwell** [comment]
@michael-letcher , @OneCyrus and @danquirk work item support provided via #87 
Should be released later in the day or tomorrow.

**Comment by OneCyrus** [comment]
awesome @mburumaxwell!

**Comment by mburumaxwell** [comment]
@michael-letcher, @OneCyrus, and @danquirk auto-approval is now supported via #89 

I will now proceed and close this issue.

**Comment by OneCyrus** [comment]
setting auto-complete works great but unfortunately, it's not setting the approval which would be the complete use case.

![image](https://user-images.githubusercontent.com/7747800/115574735-30bd4e80-a2c2-11eb-8c56-99740bcd27c1.png)
