### ISSUE TITLE
Allow custom location for configuration file

### ISSUE THREAD

**Issue by iantasker** [tinglesoftware/dependabot-azure-devops#381]
It would be really useful if a custom file paths could be added to the list of allowed file paths 

https://github.com/tinglesoftware/dependabot-azure-devops/blob/928d35912a33364e52ca3c65141225162de4b2a4/src/extension/task/utils/parseConfigFile.ts#L23

This would allow config files to reside in git submodules.

**Comment by iantasker** [comment]
```
The docker container used to run this task checks for a configuration file in the .github folder. Migrate to it.
        Using the .azuredevops folder is deprecated and will be removed in version 0.11.0.\r\n

        See https://github.com/tinglesoftware/dependabot-azure-devops#using-a-configuration-file for more information.
```

If you only want to support a single location by default fine but please allow it to be overridden. This change will really inconvenience azuredevops users.

**Comment by iantasker** [comment]
I have created PR to resolve this issue #382

**Comment by mburumaxwell** [comment]
@iantasker thanks for your suggestion. However, the warning messages is present intentionally because we read the configuration file in the Ruby script [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/358cb007be1a91f9fc7dbcb5820fb05853562e4b/src/script/update-script.rb#L254) whose data is then used to load [ignore conditions](https://github.com/tinglesoftware/dependabot-azure-devops/blob/358cb007be1a91f9fc7dbcb5820fb05853562e4b/src/script/update-script.rb#L220) and [commit message options](https://github.com/tinglesoftware/dependabot-azure-devops/blob/358cb007be1a91f9fc7dbcb5820fb05853562e4b/src/script/update-script.rb#L453) instead of wiring the logic afresh.
 
The repository that this extension is based on only reads from `.github/dependabot.yaml` or `.github/dependabot.yml` as is evident [here](https://github.com/dependabot/dependabot-core/blob/a97ae71224d54999671b81d30f91d784833a1332/common/lib/dependabot/config/file_fetcher.rb).

First step is to update that logic in the core repository.
