### ISSUE TITLE
Error when trying to fetch from ghcr image

### ISSUE THREAD

**Issue by cherealnice** [tinglesoftware/dependabot-azure-devops#542]
Hi,

I have this installed via VisualStudo Marketplace on my Azure repo.  Since Saturday, when I try to build my image I get the following error:

```docker: Error response from daemon: Head "[https://ghcr.io/v2/tingle/dependabot-azure-devops/manifests/0.15"](https://ghcr.io/v2/tingle/dependabot-azure-devops/manifests/0.15%22): denied.```

I haven't changed anything, so I believe it's an issue with this project, but please let me know if that's not the case

**Comment by cherealnice** [comment]
Full Logs:

Starting: dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.15.453
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=npm -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_TARGET_BRANCH=main -e DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"npm_registry","token":"****","replaces-base":true,"registry":"pkgs.dev.azure.com/****/_packaging/****/npm/registry/"}] -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=**** -e AZURE_PROJECT=**** -e AZURE_REPOSITORY=**** -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash -e AZURE_SET_AUTO_COMPLETE=true ghcr.io/tingle/dependabot-azure-devops:0.15
Unable to find image 'ghcr.io/tingle/dependabot-azure-devops:0.15' locally
docker: Error response from daemon: Head "[https://ghcr.io/v2/tingle/dependabot-azure-devops/manifests/0.15"](https://ghcr.io/v2/tingle/dependabot-azure-devops/manifests/0.15%22): denied.
See 'docker run --help'.
##[error]The process '/usr/bin/docker' failed with exit code 125
Finishing: dependabot

**Comment by mburumaxwell** [comment]
Where did you get that image from? We don't produce such an image. It should be `ghcr.io/tinglesoftware/dependabot-updater` for the extension.

**Comment by mburumaxwell** [comment]
Oh I suspect that you have supplied a value for the `dockerImageRepository` input. Unless you need to overrides defaults, to supplied a different image source, repository or tag, there no need to specify the `docker*` inputs.

As from version 0.15.0, the images are no published in GHCR and not Docker Hub. The extension and server components use that by default.

**Comment by cherealnice** [comment]
Strange, I don't think we added that. Is it possible that it was automatically added when I added the pipeline task in the UI? Anyway, removing dockerImageRepository fixed the issue, thanks!

**Comment by mburumaxwell** [comment]
@DaleMckeown ,
The change was mentioned in the release notes https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.15.0

Anyone using the `dockerImageRepository` or `dockerImageRegistry` inputs is an advanced user that's why it does not show up in any non-advanced examples for yaml pipelines. These are meant to control image sources for scenarios where hosting the image for self is required.

If you add the task to the classic pipelines it also does not add eh defaults. Unfortunately, if you use the GUI for yaml pipelines it does add the defaults. Unless you know why you need to specify an input, you're better off leaving it to be set by default.

**Comment by cherealnice** [comment]
@mburumaxwell It seems like the pipeline task in the Azure pipeline editor automatically adds `dockerImageRepository`. I think this was part of the confusion for me when it broke my build, since I did not have any knowledge about that field and it was automatically generated.

**Comment by DaleMckeown** [comment]
@mburumaxwell It's mostly for caching the image to try to reduce the amount of time it takes to check for all package updates.

Due to our org setup we have a DevOps project for our NuGet packages. The project contains about 25 individual repositories, each with a VS solution for a NuGet package. Each repository has a pipeline for checking dependencies with dependabot. Caching the image has reduced the time it takes to run dependency checks by about 50%

We're quite new to pipelines, if there is a more efficient way to do this, such as having one pipeline that can check dependencies in multiple repositories, I'd be greatful to hear how that can be achieved.

**Comment by mburumaxwell** [comment]
@cherealnice 
My honest opinion is that the GUI for the yaml pipelines should not generate the yaml with default values, similar to the classic one, but there's little that can be done about that at this point. Apologies for the tough time.

@DaleMckeown 
Opps! Caching is a use case what was ignored when making the changes.
There are two ways to handle multiple repositories. For repositories in one project, you can create a single pipeline with a template that iterates through a list of repositories that you provide and, in each iteration, set a different value for the `targetRepositoryName` in the task.
Alternatively, you can run the [recently open-sourced server component](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/server.md) in your Azure subscription and it will do all the magic required for your project.
We have been using the later for 2 years now to avoid congestion in our pipelines.

**Comment by DaleMckeown** [comment]
@mburumaxwell thanks for the suggestion. I'll look at the single pipeline in the first instance. If you know of any guides or links that explain that process in more detail, please throw them my way.

Thanks for the help.
