### ISSUE TITLE
[External]Download Image from ghcr with azure devops takes forever

### ISSUE THREAD

**Issue by davesmits** [tinglesoftware/dependabot-azure-devops#557]
I am pretty sure this is not really a bug or something this extension has influence over but curious if more people have the experience or know a workaround.

We notice very big difference in download time of the image. Sometimes it takes about a minutes but sometimes takes over an hour resulting in the pipeline beeing canceled

In this screenshot you see the download takes 20 minutes and still downloading.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3148438/224482094-234c5696-ed7a-446c-a40f-eefe324083ea.png">

It seems to happen since the move to ghrc with `ghcr.io/tinglesoftware/dependabot-updater:0.16` (I skipped 0.15)

I enabled caching of the image but that is not perfect solution as need to manually update the version number.

**Comment by ch0wm3in** [comment]
We experience the exact same issue since 0.16, unsure what the issue is.

**Comment by mburumaxwell** [comment]
I have been seeing this recently too when I ran some tests. Could it be that GHCR is a less capable registry compared to DockerHub? The base of the docker image is same for the last couple of months and versions which begs the question.

However, this hasn't been much of an issue since we use the [server](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/server.md) for all dependabot works expect quick repro testing which is done with the extension. That could be why we haven't felt the impact.

**Comment by mburumaxwell** [comment]
@davesmits , @ch0wm3in are you still seeing the long periods of time? It seems to have settled for us.

**Comment by davesmits** [comment]
seems not to happen anymore
