### ISSUE TITLE
Missing dependabot-updater docker image version tags

### ISSUE THREAD

**Issue by DevDavido** [tinglesoftware/dependabot-azure-devops#715]
Recently we noticed that [docker image version tags for dependabot-updater](https://github.com/tinglesoftware/dependabot-azure-devops/pkgs/container/dependabot-updater/versions?filters%5Bversion_type%5D=tagged) from 0.18.0 (patch versions) onward went missing. We used version 0.18.0 which is not available anymore, then updated to 0.18.1 which eventually also went missing. Is that intentional or accidentally? How does the release process look like for dependabot-updater?

**Comment by mburumaxwell** [comment]
The release and cleanup process are available in the .github/workflows folder.

Only the latest 20 versions are retained during cleanup every 14 days.

Unless you're testing something, there's no need to fix the version in your task. Instead, do not set the version so that the task can use the default version configured (matches its version).

If you're using the docker image elsewhere, first check if the server component serves you and use the instructions on keeping upto date available there. As an alternative, use build your own docker image and dependabot will update the image version declared on the `FROM` line.

**Comment by DevDavido** [comment]
Ok, thanks for the information and the proposed solutions.
