### ISSUE TITLE
Unable to find image /tinglesoftware/dependabot-updater-npm:latest not found. Manifest unknown error 

### ISSUE THREAD

**Issue by Sheelayathakula** [tinglesoftware/dependabot-azure-devops#734]
Hi Team,

I have integrated dependabot in my code.. currently I'm pulling the tingle/dependabot-azure-devops:0.11 image from docker hub registry and it is working fine till last week.

Now we were getting the error that tinglesoftware/dependabot-updater not found. Manifest unknown error. I have tried to check the latest image tag for dependabot-azure-devops to 0.14  but still giving the error.  

Could you please help me on what all things needs to be included to in order to make the dependabot work from azure pipelines

Thanks,

**Comment by mburumaxwell** [comment]
@Sheelayathakula 
1. Is there any specific reason you're using the old image tag? (0.11)
2. Is there a specific reason why you want to use the `latest` tag

The reason you're getting this error is because you specified the registry, repository, and tag for the docker image. A couple of days/weeks ago, we switched to a docker image per ecosystem which aligns with the change in `dependabot-core` a couple of months ago. To fix the issue you need to simplify your pipeline step for the dependabot task by removing any inputs that you do not explicitly need. The task will choose defaults and advance with them with every new release.

**Comment by Sheelayathakula** [comment]
Hello Maxwell,

Thanks for getting back to me.
1.  I'm using the latest image tag 0.14, but still having the same issue.
2.  The reason why we are specifying the repository details is because we
were pulling the latest image tag from docker hub registry and storing it
in the private repository and specifying the details so that it will pick
the latest from private acr instead of docker hub registry.

Could you please share the article or the documentation related to this?

Thanks,

**Comment by mburumaxwell** [comment]
Latest version is 1.21 

Release notes for the major change: https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.20.0

We stopped publishing to docker hub a while ago. The images are only in GitHub Container Registry.

What's wrong with using the official images we provide on GHCR?

**Comment by davhdavh** [comment]
azure devops job is failing with fresh install

```
Starting: dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.20.531
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=helm -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e DEPENDABOT_DIRECTORY=/cluster-services -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=Catglobe -e AZURE_PROJECT=Catglobe-Main -e AZURE_REPOSITORY=ServerConfiguration -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash ghcr.io/tinglesoftware/dependabot-updater-helm:1.20
Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-helm:1.20' locally
docker: Error response from daemon: Head "[https://ghcr.io/v2/tinglesoftware/dependabot-updater-helm/manifests/1.20"](https://ghcr.io/v2/tinglesoftware/dependabot-updater-helm/manifests/1.20%22): denied.
See 'docker run --help'.
##[error]The process '/usr/bin/docker' failed with exit code 125
Finishing: dependabot
```

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/1201165/a0f4d35d-d3ca-4ea6-a087-db1a2fc6fa21)

**Comment by mburumaxwell** [comment]
The error message is clear enough, there's no image like `dependabot-updater-helm`. `helm` is not an ecosystem!
To do updates for helm your existence should be docker.

Please read the official docs.

**Comment by davhdavh** [comment]
@mburumaxwell Thanks.

**Comment by Sheelayathakula** [comment]
we re using the official image provided by ghcr, but we want to pull the image from ghcr and store it in private acr and in the dependabot task we want to use the image from acr. 

Can this be possible?

**Comment by mburumaxwell** [comment]
Anything is possible but this will require lots of work for you as there are potentially 17 images that you will need to handle. Honestly, I believe there is no reason why you should be pulling the images into a custom registry because GHCR serves just well enough for both private and public projects/organizations; much better than docker hub in my opinion.

If you still have to pull the images into a private registry, then you will need a custom setup and you are on your own.

Beware that in the future, we may remove support for setting an image registry, repository, and tag because it is causing more harm that good.
