### ISSUE TITLE
auto approval

### ISSUE THREAD

**Issue by OneCyrus** [tinglesoftware/dependabot-azure-devops#95]
the new auto complete feature works so far. but to get this use case fully working we would also need the auto approval to be active.

![image](https://user-images.githubusercontent.com/7747800/115575033-77ab4400-a2c2-11eb-95e3-0806bc191c7f.png)

**Comment by mburumaxwell** [comment]
Can you contribute a PR?

**Comment by OneCyrus** [comment]
unfortunately, my time is limited for the next few weeks and I'm not familiar with ruby. do you know if this feature is already supported by dependabot core, or do we need to add the logic?

**Comment by huserben** [comment]
I could try having a look into this - I have never done ruby but I think I would manage somehow.

I would have extended the script in a similar fashion after we check whether we want to set it to autocomplete (see [line 405](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/src/script/update-script.rb#L405)).
So if we set the variable in the task to auto-approve, we'll just use the Azure DevOps REST API to approve it - would this make sense?

What I was wondering, would we need to provide the option which user actually would approve? Because in our case you cannot approve your own PRs and that makes sense, I'm not sure if Azure DevOps provides a way to exclude this for a specific user (e.g. the build service). If not we probably want to have the capability to provide an additional token of the "approving user".

What are your thoughts on this? If this sounds sane I can check it out in the next days and see what I can do.

**Comment by afrixx** [comment]
I'm not sure if this solution fits for you - but I still want to mention it shortly:

If you remove the policy for the target branch that at least one reviewer must approve, Dependabot can close the pull request directly.

**Comment by huserben** [comment]
#102 is implementing the functionality. @mburumaxwell  could you have a look and let me know whether this is acceptable?

**Comment by mburumaxwell** [comment]
Thanks, @huserben for your contribution

**Comment by huserben** [comment]
@mburumaxwell 
Do you have the next release of the Azure DevOps Task already planned? So we have a rough idea of when we'll be getting the new options? It's not urgent, more a "good to know" whether it's a matter of days or weeks.

**Comment by mburumaxwell** [comment]
@huserben, a new version has just been published.

**Comment by huserben** [comment]
Awesome, thank you for the quick response time and in general the willingness to create this extension and making it available for everyone.
